version: "3"
services:
  db:
    image: "postgres:alpine"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "my_pgadmin"
    ports:
      - "81:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db